---
driver:
  name: vagrant
  require_chef_omnibus: true
  customize:
    memory: 512

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-12.04
  run_list:
  - recipe[apt]

suites:
- name: default
  run_list:
  - recipe[graphite]
  attributes: {}
